# Generated by Django 3.1.1 on 2020-09-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient", name="name", field=models.CharField(max_length=70),
        ),
    ]
