# Generated by Django 3.1.1 on 2020-09-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_auto_20200904_2310"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="display_name",
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
