# Generated by Django 3.1.1 on 2020-09-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_tag_display_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="photo",
            field=models.ImageField(default="default.png", upload_to="recipes/"),
        ),
    ]
