# Generated by Django 3.1.1 on 2020-09-14 12:38

from django.db import migrations


def push_tags(apps, schema_editor):
    Tag = apps.get_model('recipes', 'Tag')
    if Tag.objects.exists():
        return
    tags = [
        Tag(name='breakfast', display_name='Завтрак', display_color='orange'),
        Tag(name='lunch', display_name='Обед', display_color='green'),
        Tag(name='dinner', display_name='Ужин', display_color='purple')
    ]
    Tag.objects.bulk_create(tags)


class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0010_auto_20200914_1718'),
    ]

    operations = [
        migrations.RunPython(push_tags)
    ]
