# Generated by Django 3.1.1 on 2020-09-12 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0008_auto_20200912_1854"),
        ("accounts", "0003_purchase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favorite",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorite_objects",
                to="recipes.recipe",
            ),
        ),
    ]
