# Generated by Django 3.1.1 on 2020-09-13 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20200913_1207'),
        ('accounts', '0004_auto_20200912_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='recipes.recipe'),
        ),
    ]
